MiniMart/Models/ShoppingCart.cs
using MiniMart.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniMart.Models
{
    public partial class ShoppingCart
    {
        
    }
}

MiniMart/ViewModels/ShoppingCartViewModel.cs
using MiniMart.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MiniMart.ViewModels
{
    public class ShoppingCartViewModel
    {
        [Key]
        public int Id { get; set; }
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

MiniMart/Controllers/CheckOutController.cs
using MiniMart.Models;
using MiniMart.Persistence;
using MiniMart.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniMart.Controllers
{
    [Authorize]
    public class CheckOutController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CheckOutController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            bool isValid = _unitOfWork.CheckOutRepo.CheckOrderValidity(id);

            // Verify if the Customer owns the order
            if (isValid && _unitOfWork.CheckOutRepo.GetOrder(id).Username == User.Identity.Name)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }

        // GET: CheckOut
        public ActionResult AddressAndPayment()
        {
            var cart = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext);

            if (cart.GetCartItemCount() == 0)
            {
                return View("Error");
            }

            return View();
        }

        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            order.Username = User.Identity.Name;
            order.OrderDate = DateTime.Now;

            //Process the order
            var cart = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext);
            cart.CreateOrder(order);

            return RedirectToAction("Complete", new { id = order.OrderId });
        }
    }
}

MiniMart/Controllers/ShoppingCartController.cs
using MiniMart.Models;
using MiniMart.Persistence;
using MiniMart.Repositories;
using MiniMart.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniMart.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View(new ShoppingCartViewModel
            {
                CartItems = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetCartItems(),
                CartTotal = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetTotal()
            });
        }

        public ActionResult AddToCart(int Id)
        {
            var addedProduct = _unitOfWork.ProductRepo.FindProduct(Id);

            _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).AddToCart(addedProduct);

            return View();
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int Id)
        {
            string productName = _unitOfWork.ShoppingCartRepo.GetCartById(Id).Product.Name;

            return Json(new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your shopping cart.",
                CartTotal = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetTotal(),
                CartCount = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetCount(),
                ItemCount = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).RemoveFromCart(Id),
                DeleteId = Id
            });
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            double result = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetCartItemCount();

            return PartialView("CartSummary", result);
        }

    }
}

MiniMart/Views/ShoppingCart/Index.cshtml
@model MiniMart.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

@helper formatAmount(decimal amount)
{
    @String.Format("{0:c}", amount)
}

<h3 style="background-color: white; padding: 10px; width: 220px">
    <b>Review your cart</b>
</h3>

<div id="update-message">
</div>
<table class="table" style="width:700px">
    <thead>
        <tr>
            <th>
                Product
            </th>
            <th>
                Price (each)
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody style="background-color: white; padding: 10px">
        @foreach (var item in Model.CartItems)
        {
            <tr id="row-@item.RecordId">
                <td>
                    <a href="@Url.Action("Details", new { id = item.ProductId })">
                        <img alt="@item.Product.Name" src="@item.Product.ArtUrl" width="70" height="70" />
                        <span>@item.Product.Name</span>
                    </a>
                </td>
                <td>
                    @formatAmount(@item.Product.Price)
                </td>
                <td id="item-count-@item.RecordId">
                    @item.Count
                </td>
                <td>
                    <a href="#" class="RemoveLink" data-id="@item.RecordId">
                        Remove from cart
                    </a>
                </td>
            </tr>
        }
        <tr style="background-color: #5bc0de; color: white; font-size: 20px">
            <td>
                <b>Total</b>
            </td>
            <td></td>
            <td></td>
            <td id="cart-total">
                @formatAmount(@Model.CartTotal)
            </td>
        </tr>
    </tbody>
</table>

<p>
    @Html.ActionLink("Continue Shopping", "Index", "Products", "", new { @class = "btn continue-shopping-btn"})
    @Html.ActionLink("Checkout>>", "AddressAndPayment", "CheckOut", "", new { @class = "btn btn-info" })
</p>


@section scripts{
    <script type="text/javascript">
        $(function () {
            // Document.ready -> link up remove event handler
            $(".RemoveLink").click(function () {
                // Get the id from the link
                var recordToDelete = $(this).attr("data-id");
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.ItemCount == 0) {
                                $('#row-' + data.DeleteId).fadeOut('slow');
                            } else {
                                $('#item-count-' + data.DeleteId).text(data.ItemCount);
                            }
                            $('#cart-total').text(data.CartTotal);
                            $('#update-message').text(data.Message);
                            $('#cart-status').text('Cart (' + data.CartCount + ')');
                        });
                }
            });
        });
    </script>
}