MiniMart/Controllers/ShoppingCartController.cs
using MiniMart.Models;
using MiniMart.Persistence;
using MiniMart.Repositories;
using MiniMart.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniMart.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View(new ShoppingCartViewModel
            {
                CartItems = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetCartItems(),
                CartTotal = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetTotal()
            });
        }

        public ActionResult AddToCart(int Id)
        {
            var addedProduct = _unitOfWork.ProductRepo.FindProduct(Id);

            _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).AddToCart(addedProduct);

            return View();
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int Id)
        {
            string productName = _unitOfWork.ShoppingCartRepo.GetCartById(Id).Product.Name;

            return Json(new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your shopping cart.",
                CartTotal = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetTotal(),
                CartCount = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetCount(),
                ItemCount = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).RemoveFromCart(Id),
                DeleteId = Id
            });
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            double result = _unitOfWork.ShoppingCartRepo.GetCart(this.HttpContext).GetCartItemCount();

            return PartialView("CartSummary", result);
        }

    }
}

MiniMart/Views/Shared/CartSummary.cshtml
@model double

@Html.ActionLink("Cart (" + Model + ")", "Index", "ShoppingCart", new { id = "cart-status" })

MiniMart/Views/Shared/CategoryListPartialView.cshtml
@model IEnumerable<MiniMart.Models.Category>


@foreach (var item in Model)
{
    <ul id="category-list">
        <li>
            <a href="@Url.Action("Browse", new { category = item.Name})">@item.Name</a>
        </li>
    </ul>

}

MiniMart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MiniMart</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="sidenav">
        <p>Categories</p>
        @Html.Action("CategoryList", "Products")
    </div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MiniMart", "Index", "Products", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    <li>@Html.Action("CartSummary", "ShoppingCart")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MiniMart</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>